### ISSUE TITLE
BUG: IndexOutOfBoundsException when switching scene to GameScene.

### ISSUE THREAD

**Issue by Uggah** [maxknerrich/JavaChess#23]
Stack Trace:
```
Exception in thread "JavaFX Application Thread" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at javafx.fxml@18/javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1857)
	at javafx.fxml@18/javafx.fxml.FXMLLoader$ControllerMethodEventHandler.handle(FXMLLoader.java:1724)
	at javafx.base@18/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at javafx.base@18/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
	at javafx.base@18/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at javafx.base@18/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at javafx.base@18/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base@18/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@18/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@18/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@18/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@18/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@18/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base@18/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.base@18/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.graphics@18/javafx.scene.Node.fireEvent(Node.java:8797)
	at javafx.controls@18/javafx.scene.control.Button.fire(Button.java:203)
	at javafx.controls@18/com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:208)
	at javafx.controls@18/com.sun.javafx.scene.control.inputmap.InputMap.handle(InputMap.java:274)
	at javafx.base@18/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:247)
	at javafx.base@18/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at javafx.base@18/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
	at javafx.base@18/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at javafx.base@18/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at javafx.base@18/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base@18/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@18/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@18/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@18/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@18/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@18/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base@18/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.base@18/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.graphics@18/javafx.scene.Scene$MouseHandler.process(Scene.java:3881)
	at javafx.graphics@18/javafx.scene.Scene.processMouseEvent(Scene.java:1874)
	at javafx.graphics@18/javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2607)
	at javafx.graphics@18/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:411)
	at javafx.graphics@18/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:301)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at javafx.graphics@18/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:450)
	at javafx.graphics@18/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:424)
	at javafx.graphics@18/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:449)
	at javafx.graphics@18/com.sun.glass.ui.View.handleMouseEvent(View.java:551)
	at javafx.graphics@18/com.sun.glass.ui.View.notifyMouse(View.java:937)
	at javafx.graphics@18/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics@18/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:316)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at com.sun.javafx.reflect.Trampoline.invoke(MethodUtil.java:77)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at javafx.base@18/com.sun.javafx.reflect.MethodUtil.invoke(MethodUtil.java:275)
	at javafx.fxml@18/com.sun.javafx.fxml.MethodHelper.invoke(MethodHelper.java:84)
	at javafx.fxml@18/javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1852)
	... 46 more
Caused by: java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 1
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at javafx.base@18/com.sun.javafx.collections.ObservableListWrapper.get(ObservableListWrapper.java:89)
	at javafx.base@18/com.sun.javafx.collections.VetoableListDecorator.get(VetoableListDecorator.java:305)
	at javafx.controls@18/javafx.scene.control.skin.TextAreaSkin$ContentView.layoutChildren(TextAreaSkin.java:1393)
	at javafx.graphics@18/javafx.scene.Parent.layout(Parent.java:1207)
	at javafx.graphics@18/javafx.scene.Parent.layout(Parent.java:1214)
	at javafx.graphics@18/javafx.scene.Parent.layout(Parent.java:1214)
	at javafx.graphics@18/javafx.scene.Parent.layout(Parent.java:1214)
	at javafx.graphics@18/javafx.scene.Parent.layout(Parent.java:1214)
	at javafx.graphics@18/javafx.scene.Parent.layout(Parent.java:1214)
	at javafx.graphics@18/javafx.scene.Parent.layout(Parent.java:1214)
	at javafx.graphics@18/javafx.scene.Parent.layout(Parent.java:1214)
	at javafx.graphics@18/javafx.scene.Scene.doLayoutPass(Scene.java:579)
	at javafx.graphics@18/javafx.scene.Scene.preferredSize(Scene.java:1773)
	at javafx.graphics@18/javafx.scene.Scene$2.preferredSize(Scene.java:396)
	at javafx.graphics@18/com.sun.javafx.scene.SceneHelper.preferredSize(SceneHelper.java:66)
	at javafx.graphics@18/javafx.stage.Window$SceneModel.invalidated(Window.java:867)
	at javafx.base@18/javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:112)
	at javafx.base@18/javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:147)
	at javafx.graphics@18/javafx.stage.Window.setScene(Window.java:823)
	at javafx.graphics@18/javafx.stage.Stage.setScene(Stage.java:270)
	at JavaChess@1.0-SNAPSHOT/com.gameofjess.javachess.gui.controller.Controller.switchScene(Controller.java:71)
	at JavaChess@1.0-SNAPSHOT/com.gameofjess.javachess.gui.controller.MenuController.joinGame(MenuController.java:207)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	... 53 more
```

Description:

When joining or hosting a game, the scene is not properly loaded. This only happened when another player is already on the server and the match begins right after joining. Only happening sometimes, far from regularly.

**Comment by Uggah** [comment]
```
Exception in thread "JavaFX Application Thread" java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 1
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at javafx.base@18/com.sun.javafx.collections.ObservableListWrapper.get(ObservableListWrapper.java:89)
	at javafx.base@18/com.sun.javafx.collections.VetoableListDecorator.get(VetoableListDecorator.java:305)
	at javafx.controls@18/javafx.scene.control.skin.TextAreaSkin$ContentView.layoutChildren(TextAreaSkin.java:1393)
	at javafx.graphics@18/javafx.scene.Parent.layout(Parent.java:1207)
	at javafx.graphics@18/javafx.scene.Parent.layout(Parent.java:1214)
	at javafx.graphics@18/javafx.scene.Parent.layout(Parent.java:1214)
	at javafx.graphics@18/javafx.scene.Parent.layout(Parent.java:1214)
	at javafx.graphics@18/javafx.scene.Parent.layout(Parent.java:1214)
	at javafx.graphics@18/javafx.scene.Parent.layout(Parent.java:1214)
	at javafx.graphics@18/javafx.scene.Parent.layout(Parent.java:1214)
	at javafx.graphics@18/javafx.scene.Parent.layout(Parent.java:1214)
	at javafx.graphics@18/javafx.scene.Scene.doLayoutPass(Scene.java:579)
	at javafx.graphics@18/javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2499)
	at javafx.graphics@18/com.sun.javafx.tk.Toolkit.lambda$runPulse$2(Toolkit.java:405)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at javafx.graphics@18/com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:404)
	at javafx.graphics@18/com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:434)
	at javafx.graphics@18/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:575)
	at javafx.graphics@18/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:555)
	at javafx.graphics@18/com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:548)
	at javafx.graphics@18/com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:352)
	at javafx.graphics@18/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics@18/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics@18/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:316)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

Similar problem, yet another stacktrace.
